#![allow(unused_imports)]
#![allow(clippy::all)]
use wasm_bindgen::prelude::*;
use js_sys::{Array, Function, Object, Promise};
#[wasm_bindgen]
extern "C" {
    ///Functions for testing binary data request/response parameters. The first two just return back the bytes they were passed in an array.
    #[wasm_bindgen(js_namespace = ["chrome", "idltest"], js_name = "sendArrayBuffer")]
    pub fn send_array_buffer(input: ::js_sys::ArrayBuffer) -> Promise;
    ///TODO(asargent) - we currently can't have [instanceOf=ArrayBufferView], I think because ArrayBufferView isn't an instantiable type. The best we might be able to do is have a 'choices' list including all the typed array subclasses like Uint8Array, Uint16Array, Float32Array, etc.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "idltest"],
        js_name = "sendArrayBufferView"
    )]
    pub fn send_array_buffer_view(input: ::js_sys::ArrayBuffer) -> Promise;
    ///
    #[wasm_bindgen(js_namespace = ["chrome", "idltest"], js_name = "getArrayBuffer")]
    pub fn get_array_buffer() -> Promise;
    ///This function should not have C++ code autogenerated (the variable name |switch| should cause compile errors if it does). But the name should get defined and made visible from within extensions/apps code.
    #[wasm_bindgen(js_namespace = ["chrome", "idltest"], js_name = "nocompileFunc")]
    pub fn nocompile_func(switch: i32);
}
