#![allow(unused_imports)]
#![allow(clippy::all)]
use js_sys::{Array, Function, Object, Promise};
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    ///Fetches the value of the device identifier of the directory API, that is generated by the server and identifies the cloud record of the device for querying in the cloud directory API. If the current user is not affiliated, returns an empty string.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "enterprise",
        "deviceAttributes"],
        js_name = "getDirectoryDeviceId"
    )]
    pub fn get_directory_device_id() -> Promise;
    ///Fetches the device's serial number. Please note the purpose of this API is to administrate the device (e.g. generating Certificate Sign Requests for device-wide certificates). This API may not be used for tracking devices without the consent of the device's administrator. If the current user is not affiliated, returns an empty string.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "enterprise",
        "deviceAttributes"],
        js_name = "getDeviceSerialNumber"
    )]
    pub fn get_device_serial_number() -> Promise;
    ///Fetches the administrator-annotated Asset Id. If the current user is not affiliated or no Asset Id has been set by the administrator, returns an empty string.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "enterprise",
        "deviceAttributes"],
        js_name = "getDeviceAssetId"
    )]
    pub fn get_device_asset_id() -> Promise;
    ///Fetches the administrator-annotated Location. If the current user is not affiliated or no Annotated Location has been set by the administrator, returns an empty string.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "enterprise",
        "deviceAttributes"],
        js_name = "getDeviceAnnotatedLocation"
    )]
    pub fn get_device_annotated_location() -> Promise;
    ///Fetches the device's hostname as set by DeviceHostnameTemplate policy. If the current user is not affiliated or no hostname has been set by the enterprise policy, returns an empty string.
    #[wasm_bindgen(
        js_namespace = ["chrome",
        "enterprise",
        "deviceAttributes"],
        js_name = "getDeviceHostname"
    )]
    pub fn get_device_hostname() -> Promise;
}
